CREATE DATABASE TIENDA;

USE TIENDA;

CREATE TABLE PRODUCTO(
	IDPRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
	NOMBREPRODUCTO VARCHAR(50) NOT NULL,
    PRECIOPRODUCTO decimal(10,2) NOT NULL,
    FECHAVENTA date DEFAULT '0000-00-00'
);

SHOW COLUMNS FROM PRODUCTO;

